### ISSUE TITLE
Foodie Pro conflict

### ISSUE THREAD

**Issue by cdils** [cdils/genesis-style-trump#3]
Changes made via Theme Customizer (i.e. colors, fonts) do not display when GST plugin is active.

**Comment by psergerie** [comment]
Hi Carrie,

Sorry to jump in after almost 2 years but i am new to the wordpress / genesis community.  I have learned a lot in the past few months through your carriedils.com site and notice that this issue does not seem to be resolved.  I am using the foodie pro theme and did some customization up now.  I am having a hard time customizing woocommerce styles.  It seems that when enqueuing the foodie styles sheet after woocommerce styles sheet, the foodie pro customizer is useless.  Any development since this post ?  Do i need to play with the enqueuing priority ?

Best regards,

Patrick

**Comment by seothemes** [comment]
I don't use foodie pro but had a similar issue the other day. My guess is that the customizer is outputting inline CSS before the main stylesheet. Try changing the wp_add_inline_style function to a higher priority. Possibly in lib/customizer.php

https://codex.wordpress.org/Function_Reference/wp_add_inline_style

**Comment by seothemes** [comment]
@psergerie did you manage to figure this out? If not, I've created a pull request with a fix for the Foodie Pro conflict here #9

**Comment by cdils** [comment]
Thanks @seothemes. Sorry I missed the PR when you posted it. Just merged into the [develop](https://github.com/cdils/genesis-style-trump/tree/develop) branch

**Comment by psergerie** [comment]
Hi Carry,

I have just implemented the additional case into the GST php file and everything now works great !

Still learning a lot from experts like you !

Thanks again !  Hope I’ll be able to give back soon to the Genesis community…

Regards,

Patrick

**Comment by cdils** [comment]
@psergerie  All thanks to @seothemes for this one. :) I'll push the update to the WP.org repo soon.
